# Generated by Django 5.2.6 on 2025-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institute',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
