# Generated by Django 5.2.6 on 2025-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_cgpa_remove_userprofile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='detailed_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
